### ISSUE TITLE
Uncaught AnalyticsParametersRequiredError: The Analytics library must be initialized with analyticsParameters to call verifyBuyer

### ISSUE THREAD

**Issue by spenweb** [square/react-square-payment-form#74]
I get this error when submitting the payment form which prevents the submission to complete. I could not find a reference to the "Analytics library" or "analyticsParameters". Direct link to Squareup documentation: https://developer.squareup.com/docs/api/paymentform#verifybuyer.
Error in JavaScript Console:
```
data.js:15 Uncaught AnalyticsParametersRequiredError: The Analytics library must be initialized with analyticsParameters to call verifyBuyer.
    at r (https://js.squareupsandbox.com/payments/data.js:15:1054)
    at Object.AnalyticsParametersRequiredError (https://js.squareupsandbox.com/payments/data.js:15:1195)
    at s.verifyBuyer (https://js.squareupsandbox.com/payments/data.js:10:20066)
    at Object.verifyBuyer (https://js.squareupsandbox.com/v2/paymentform:1:83642)
    at St.verifyBuyer (https://js.squareupsandbox.com/v2/paymentform:1:158157)
    at Object.cardNonceResponseReceived [as current] (http://localhost:3000/static/js/1.chunk.js:248450:32)
    at http://localhost:3000/static/js/1.chunk.js:248750:24
    at mt._cardNonceResponseReceived (https://js.squareupsandbox.com/v2/paymentform:1:153528)
    at mt.receiveMessageCallback (https://js.squareupsandbox.com/v2/paymentform:1:149993)
r @ data.js:15
AnalyticsParametersRequiredError @ data.js:15
s.verifyBuyer @ data.js:10
verifyBuyer @ paymentform:1
St.verifyBuyer @ paymentform:1
cardNonceResponseReceived @ SquarePaymentForm.tsx:133
(anonymous) @ useDynamicCallback.ts:8
mt._cardNonceResponseReceived @ paymentform:1
mt.receiveMessageCallback @ paymentform:1
```

**Comment by DavidRagone** [comment]
Sorry for the delay! Are you still seeing this error?
